version: '3.8'

services:
  frontend: 
    image: mihailkasev/infra_frontend:latest
    volumes: 
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  postgres:
    image: postgres:14.4-alpine
    volumes:
      - foodgram_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: mihailkasev/infra_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/ 
    depends_on:
      - postgres
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend-static/
      - media_value:/var/html/backend-media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  foodgram_data:
