# Generated by Django 2.2.16 on 2022-12-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221219_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'default_related_name': 'ingridients_recipe', 'verbose_name': 'Ингредиент в рецепте'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='recipes/images', verbose_name='Картинка'),
        ),
    ]
