# Generated by Django 2.2.16 on 2022-12-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221221_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': ('Пользователь',), 'verbose_name_plural': ('Пользователи',)},
        ),
    ]
